# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "katzenpost-daemons-unstable-${version}";
  version = "2018-01-31-1930";

  goPackagePath = "github.com/katzenpost/daemons";
  subPackages = [ "authority/nonvoting" "server" "mailproxy" ];

  src = fetchgit {
    url = "https://github.com/katzenpost/daemons";
    rev = "d34972c96e36a494925c52c78145cfd921f34525";
    sha256 = "178rzkn20ir2kvsyzlr3wmj3zw2yixkqy6hxy1i7q7va4knw4wvw";
  };

  goDeps = ./deps.nix;

  meta = {
    description = "Katzenpost -- Traffic analysis resistant messaging";
    homepage = "https://katzenpost.mixnetworks.org/";
    platforms = stdenv.lib.platforms.unix;
    license = stdenv.lib.licenses.agpl3;
    maintainers = with stdenv.lib.maintainers; [  ];
  };
}
