# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "767c40d6a2e058483c25fa193e963a22da17236d";
      sha256 = "0bjqngwwh58jphf542g8k8ancw33fy8n5r3hymi1bzrbw1war4j4";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/aez.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/aez";
      rev = "4dad034d9db2caec23fb8f69b9160ae16f8d46a3";
      sha256 = "164p139i755cvi1291drh50j3c8l6igfhpvyf3fpvipvyvqm5x5f";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/bloom.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/bloom";
      rev = "5249ee52905a9ee3a7faa71c7c9395b61815ddd1";
      sha256 = "14l1ipkk4kk7x22chn7czg6n1dr8ch6vfhsqciacanwlxjkkf82w";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/bsaes.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/bsaes";
      rev = "e06297f34865a50b8e473105e52cb64ad1b55da8";
      sha256 = "1wgczhx66pxph1h7778c1arxihicngvxyrvwgx4hx4wrlr28fcrx";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/chacha20.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/chacha20";
      rev = "e3b1f968fc6397b51d963fee8ec8711a47bc0ce8";
      sha256 = "16cqsn7agk5jbxh6p5lvn18ygy7hqx824rldg82xhsqj5dyzcd98";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/newhope.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/newhope";
      rev = "9598792ba8f205d72c9b5b639b0d2827cbb7d8b9";
      sha256 = "1c9wy0l0xfinzzmjyjjwd7d3l2d8aj0sbcbhhwq1kbilbgxap8ni";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "b26d9c308763d68093482582cea63d69be07a0f0";
      sha256 = "0k7v2i1d2d6si8gswn83qb84czhhia53v2wdy33yz9ppdidxk0ry";
    };
  }
  {
    goPackagePath = "github.com/agl/ed25519";
    fetch = {
      type = "git";
      url = "https://github.com/agl/ed25519";
      rev = "5312a61534124124185d41f09206b9fef1d88403";
      sha256 = "1v8mhkf1m3ga5262s75vabskxvsw5rpqvi5nwhxwiv7gfk6h823i";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/template";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/template";
      rev = "a0175ee3bccc567396460bf5acd36800cb10c49c";
      sha256 = "0qjgvvh26vk1cyfq9fadyhfgdj36f1iapbmr5xp6zqipldz8ffxj";
    };
  }
  {
    goPackagePath = "github.com/alecthomas/units";
    fetch = {
      type = "git";
      url = "https://github.com/alecthomas/units";
      rev = "2efee857e7cfd4f3d0138cc3cbb1b4966962b93a";
      sha256 = "1j65b91qb9sbrml9cpabfrcf07wmgzzghrl7809hjjhrmbzri5bl";
    };
  }
  {
    goPackagePath = "github.com/cockroachdb/apd";
    fetch = {
      type = "git";
      url = "https://github.com/cockroachdb/apd";
      rev = "b1ce49cb2a474f4416531e7395373eaafaa4fbe2";
      sha256 = "0zwjg3zsr5pl9fsv19nv9lf9x2ri184nsfz210kmfj6r8iajzh45";
    };
  }
  {
    goPackagePath = "github.com/coreos/bbolt";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/bbolt";
      rev = "48ea1b39c25fc1bab3506fbc712ecbaa842c4d2d";
      sha256 = "0r39wj5fv6d7nkkirjnnrnhikcp6sqa5dgmr6cimz5s0smvfm8vw";
    };
  }
  {
    goPackagePath = "github.com/davecgh/go-spew";
    fetch = {
      type = "git";
      url = "https://github.com/davecgh/go-spew";
      rev = "346938d642f2ec3594ed81d874461961cd0faa76";
      sha256 = "0d4jfmak5p6lb7n2r6yvf5p1zcw0l8j74kn55ghvr7zr7b7axm6c";
    };
  }
  {
    goPackagePath = "github.com/dchest/siphash";
    fetch = {
      type = "git";
      url = "https://github.com/dchest/siphash";
      rev = "42ba037e748c9062a75e0924705c43b893edefcd";
      sha256 = "0ar74f8jgqa5cyr3kx1pj2wq9w6aavxkg0xfp6qq8f651lqanxfl";
    };
  }
  {
    goPackagePath = "github.com/eapache/queue";
    fetch = {
      type = "git";
      url = "https://github.com/eapache/queue";
      rev = "44cc805cf13205b55f69e14bcb69867d1ae92f98";
      sha256 = "07dp54n94gn3gsvdcki56yqh7py7wqqigxbamhxwgbr05n61fqyg";
    };
  }
  {
    goPackagePath = "github.com/emersion/go-message";
    fetch = {
      type = "git";
      url = "https://github.com/emersion/go-message";
      rev = "1716e3f473f914d0f63389271fbe851c749e0ab4";
      sha256 = "1yv8jw34hhdds66j547xw21z7rbzrxvdghdm1kwaxr006kw85ihi";
    };
  }
  {
    goPackagePath = "github.com/emersion/go-textwrapper";
    fetch = {
      type = "git";
      url = "https://github.com/emersion/go-textwrapper";
      rev = "d0e65e56babe3f687ff94c1d764ca0e6aa7723ee";
      sha256 = "1nw8qpjjbpkz49wd19yg2qsln1dmdfxi83wp2aa819cv6xxf2y7l";
    };
  }
  {
    goPackagePath = "github.com/flynn/noise";
    fetch = {
      type = "git";
      url = "https://github.com/flynn/noise";
      rev = "01638cb52dafe42224b938fb517721f984c03100";
      sha256 = "1rw2bjl4d67ahlkzyiyrc0sk3yf0i24adkx7pn4mdkffys7kh6d5";
    };
  }
  {
    goPackagePath = "github.com/go-stack/stack";
    fetch = {
      type = "git";
      url = "https://github.com/go-stack/stack";
      rev = "259ab82a6cad3992b4e21ff5cac294ccb06474bc";
      sha256 = "0irkqifyj84cbnq4n66ax2r591id2285diw5hzcz2k3bga8d8lqr";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "925541529c1fa6821df4e44ce2723319eb2be768";
      sha256 = "1d3zjvhl115l23xakj0014qpjchivlg098h10v5nfirkk1i9f9sa";
    };
  }
  {
    goPackagePath = "github.com/hashicorp/go-version";
    fetch = {
      type = "git";
      url = "https://github.com/hashicorp/go-version";
      rev = "4fe82ae3040f80a03d04d2cccb5606a626b8e1ee";
      sha256 = "0gq4207s1yf2nq4c2ir3bsai29svzz4830g1vbvzdrpis58r1x4m";
    };
  }
  {
    goPackagePath = "github.com/jackc/fake";
    fetch = {
      type = "git";
      url = "https://github.com/jackc/fake";
      rev = "812a484cc733c387d8dcf11ce9b15d75e0ddb865";
      sha256 = "0f32qgzhx7pl3s0g4v916z21kfyh5v1dv28aakxisiw23936wf68";
    };
  }
  {
    goPackagePath = "github.com/jackc/pgx";
    fetch = {
      type = "git";
      url = "https://github.com/jackc/pgx";
      rev = "da3231b0b66e2e74cdb779f1d46c5e958ba8be27";
      sha256 = "0y0wdbii4prw084ac05ybkrrdmd3n1rccd8dijlc8qd5sb231y3h";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/authority";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/authority";
      rev = "58fd1618e4ef3a1c5d4cd4ec31ef32a499e1b911";
      sha256 = "1ccpkbnw83s4bdn58558cvq31mnn206s8vi3vp49cd1v97kpbpgw";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/core";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/core";
      rev = "fdab27bf2aba871442bb8cec23cbd9efa293e26e";
      sha256 = "1gdmsijhz9xyscja3v927pp8m8k3w9a6qbfvlivdypz7c4da3m8a";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/mailproxy";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/mailproxy";
      rev = "2c6fa7b90bcf0c60838df117129fdf4616672a3f";
      sha256 = "1pwr73dkxbdi24r31a3wd37yibfsqpspj1910mkz1f2hgd3n55zy";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/minclient";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/minclient";
      rev = "63be5c6ebedc437b012c31934cdf695710337622";
      sha256 = "1rsaknrlkmvnsflfzhk05kgyv1g7wx4v4qw2vba1kv1m2k9lf4px";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/noise";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/noise";
      rev = "330b6cee8864fff2bad72f3d6cd6ba1dcdb2b877";
      sha256 = "0606id2rhgc87j6dyj2c1brbxw9pa0fq3al0h1gp51r9i2pig7n8";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/server";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/server";
      rev = "4886d60e5f344f152bab10392a5112456c2d45a6";
      sha256 = "1dw90n7mcy727ff064q32ag311yn3yxr2nsi5jy5fwgghppnnijj";
    };
  }
  {
    goPackagePath = "github.com/lib/pq";
    fetch = {
      type = "git";
      url = "https://github.com/lib/pq";
      rev = "88edab0803230a3898347e77b474f8c1820a1f20";
      sha256 = "02y7c8xy33x5q4167x2drzrys41nfi7wxxp9hy4vpazfws88al9p";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-colorable";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-colorable";
      rev = "167de6bfdfba052fa6b2d3664c8f5272e23c9072";
      sha256 = "1nwjmsppsjicr7anq8na6md7b1z84l9ppnlr045hhxjvbkqwalvx";
    };
  }
  {
    goPackagePath = "github.com/mattn/go-isatty";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-isatty";
      rev = "0360b2af4f38e8d38c7fce2a9f4e702702d73a39";
      sha256 = "06w45aqz2a6yrk25axbly2k5wmsccv8cspb94bfmz4izvw8h927n";
    };
  }
  {
    goPackagePath = "github.com/op/go-logging";
    fetch = {
      type = "git";
      url = "https://github.com/op/go-logging";
      rev = "b2cb9fa56473e98db8caba80237377e83fe44db5";
      sha256 = "01a6lkpj5p82gplddh55az194s9y3014p4j8x4zc8yv886z9c8gn";
    };
  }
  {
    goPackagePath = "github.com/pkg/errors";
    fetch = {
      type = "git";
      url = "https://github.com/pkg/errors";
      rev = "645ef00459ed84a119197bfb8d8205042c6df63d";
      sha256 = "001i6n71ghp2l6kdl3qq1v2vmghcz3kicv9a5wgcihrzigm75pp5";
    };
  }
  {
    goPackagePath = "github.com/pmezard/go-difflib";
    fetch = {
      type = "git";
      url = "https://github.com/pmezard/go-difflib";
      rev = "792786c7400a136282c1664665ae0a8db921c6c2";
      sha256 = "0c1cn55m4rypmscgf0rrb88pn58j3ysvc2d0432dp3c6fqg6cnzw";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "f58768cc1a7a7e77a3bd49e98cdd21419399b6a3";
      sha256 = "1j4s5pfg2ldm35y8ls8jah4dya2grfnx2drb4jcbjsyrp4cm5yfb";
    };
  }
  {
    goPackagePath = "github.com/shopspring/decimal";
    fetch = {
      type = "git";
      url = "https://github.com/shopspring/decimal";
      rev = "9ca7f51822d222ae4e246f070f9aad863599bd1a";
      sha256 = "1k7vasnhhc15k5n9ji9vbkgf9yyp4vndw94xyac2jbikqls385v6";
    };
  }
  {
    goPackagePath = "github.com/siebenmann/smtpd";
    fetch = {
      type = "git";
      url = "https://github.com/siebenmann/smtpd";
      rev = "b93303610bbe1b2cc570daff2de7d77dfac329a0";
      sha256 = "1vncxcvm6rf1l5wcr29jl3gb2m6dvln8bvk7cgsj8r0jhnjikmy0";
    };
  }
  {
    goPackagePath = "github.com/sirupsen/logrus";
    fetch = {
      type = "git";
      url = "https://github.com/sirupsen/logrus";
      rev = "d682213848ed68c0a260ca37d6dd5ace8423f5ba";
      sha256 = "0nzyqwzx3k7nqfq8q7yv32gaf3ymq3bpwhkmw1hj2zakq5a93d8x";
    };
  }
  {
    goPackagePath = "github.com/stretchr/testify";
    fetch = {
      type = "git";
      url = "https://github.com/stretchr/testify";
      rev = "12b6f73e6084dad08a7c6e575284b177ecafbc71";
      sha256 = "01f80s0q64pw5drfgqwwk1wfwwkvd2lhbs56lhhkff4ni83k73fd";
    };
  }
  {
    goPackagePath = "github.com/ugorji/go";
    fetch = {
      type = "git";
      url = "https://github.com/ugorji/go";
      rev = "9831f2c3ac1068a78f50999a30db84270f647af6";
      sha256 = "0qxdq599sjwb03znlxy634mdnmfl90770wf1kk37dhzll6i84vkr";
    };
  }
  {
    goPackagePath = "go.uber.org/atomic";
    fetch = {
      type = "git";
      url = "https://github.com/uber-go/atomic";
      rev = "8474b86a5a6f79c443ce4b2992817ff32cf208b8";
      sha256 = "166shnjw8rvjvksymi2gqw1ygsbxlq15xb10j2dx5rwy4y4asq8x";
    };
  }
  {
    goPackagePath = "go.uber.org/multierr";
    fetch = {
      type = "git";
      url = "https://github.com/uber-go/multierr";
      rev = "3c4937480c32f4c13a875a1829af76c98ca3d40a";
      sha256 = "1slfc6syvw8cvr6rbrjsy6ja5w8gsx0f8aq8qm16rp2x5c2pj07w";
    };
  }
  {
    goPackagePath = "go.uber.org/zap";
    fetch = {
      type = "git";
      url = "https://github.com/uber-go/zap";
      rev = "35aad584952c3e7020db7b839f6b102de6271f89";
      sha256 = "0n79ir7jcr7s51j85swji7an0jgy1w5dxg1g68j722rmpbvsagwv";
    };
  }
  {
    goPackagePath = "go4.org";
    fetch = {
      type = "git";
      url = "https://github.com/camlistore/go4";
      rev = "fba789b7e39ba524b9e60c45c37a50fae63a2a09";
      sha256 = "01irxqy8na646b4zbw7v3zwy3yx9m7flhim5c3z4lzq5hiy2h75i";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "1875d0a70c90e57f11972aefd42276df65e895b9";
      sha256 = "1kprrdzr4i4biqn7r9gfxzsmijya06i9838skprvincdb1pm0q2q";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "0ed95abb35c445290478a5348a7b38bb154135fd";
      sha256 = "1v7yhcgqj0fy7rsliijw2iwmvyd85hqshrhh2n083x62kw9n9nsl";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "a032972e28060ca4f5644acffae3dfc268cc09db";
      sha256 = "1gx7gly2350c1nqlqys7icpyc13khp4h6klb282nc1mjbnpyk0dz";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "ff2a66f350cefa5c93a634eadb5d25bb60c85a9c";
      sha256 = "13zkhgdccsaqflz7vwxyk3bf57yz0s6vn4sf10zhmyznd99ha4cv";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "e19ae1496984b1c655b8044a65c0300a3c878dd3";
      sha256 = "1cvnnx8nwx5c7gr6ajs7sldhbqh52n7h6fsa3i21l2lhx6xrsh4w";
    };
  }
  {
    goPackagePath = "golang.org/x/tools";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/tools";
      rev = "66487607e2081c7c2af2281c62c14ee000d5024b";
      sha256 = "03wiraqkms4jb5gi7vmp52mpmp4av08yw4gr2nk31c2rnhyd3jv4";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "f7618f4b41caffc0e9f141e6f67957587341dde2";
      sha256 = "0318n37i2l5sbwx6v1rjhmwsbq4xgljr3dqa25kng1kwpdqasz2f";
    };
  }
  {
    goPackagePath = "google.golang.org/appengine";
    fetch = {
      type = "git";
      url = "https://github.com/golang/appengine";
      rev = "150dc57a1b433e64154302bdc40b6bb8aefa313a";
      sha256 = "0w3knznv39k8bm85ri62f83czcrxknql7dv6p9hk1a5jx3xljgxq";
    };
  }
  {
    goPackagePath = "gopkg.in/alecthomas/kingpin.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/alecthomas/kingpin.v2";
      rev = "947dcec5ba9c011838740e680966fd7087a71d0d";
      sha256 = "0mndnv3hdngr3bxp7yxfd47cas4prv98sqw534mx7vp38gd88n5r";
    };
  }
  {
    goPackagePath = "gopkg.in/check.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/check.v1";
      rev = "20d25e2804050c1cd24a7eea1e7a6447dd0e74ec";
      sha256 = "0k1m83ji9l1a7ng8a7v40psbymxasmssbrrhpdv2wl4rhs0nc3np";
    };
  }
  {
    goPackagePath = "gopkg.in/eapache/channels.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/eapache/channels.v1";
      rev = "47238d5aae8c0fefd518ef2bee46290909cf8263";
      sha256 = "179ryd2rqsccnv5nk35f8j4nfbqr8cgb2bjm0j8isvf5nzks8s9y";
    };
  }
  {
    goPackagePath = "gopkg.in/inconshreveable/log15.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/inconshreveable/log15.v2";
      rev = "0decfc6c20d9ca0ad143b0e89dcaa20f810b4fb3";
      sha256 = "0wx5vv219f90g3g1ack1jr8hhdw4yhhhv7j48ir4w36p8m457hdq";
    };
  }
  {
    goPackagePath = "gopkg.in/op/go-logging.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/op/go-logging.v1";
      rev = "b2cb9fa56473e98db8caba80237377e83fe44db5";
      sha256 = "01a6lkpj5p82gplddh55az194s9y3014p4j8x4zc8yv886z9c8gn";
    };
  }
  {
    goPackagePath = "gopkg.in/square/go-jose.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/square/go-jose.v2";
      rev = "f8f38de21b4dcd69d0413faf231983f5fd6634b1";
      sha256 = "1bjrs3xq3m2ckfds0l4wqf81311ymm9agipmkllbvkadac156dsa";
    };
  }
]
