# This file was generated by https://github.com/kamilchm/go2nix v2.0-dev
[
  {
    goPackagePath = "git.schwanenlied.me/yawning/aez.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/aez";
      rev = "4dad034d9db2caec23fb8f69b9160ae16f8d46a3";
      sha256 = "164p139i755cvi1291drh50j3c8l6igfhpvyf3fpvipvyvqm5x5f";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/bloom.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/bloom";
      rev = "5249ee52905a9ee3a7faa71c7c9395b61815ddd1";
      sha256 = "14l1ipkk4kk7x22chn7czg6n1dr8ch6vfhsqciacanwlxjkkf82w";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/bsaes.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/bsaes";
      rev = "e06297f34865a50b8e473105e52cb64ad1b55da8";
      sha256 = "1wgczhx66pxph1h7778c1arxihicngvxyrvwgx4hx4wrlr28fcrx";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/chacha20.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/chacha20";
      rev = "e3b1f968fc6397b51d963fee8ec8711a47bc0ce8";
      sha256 = "16cqsn7agk5jbxh6p5lvn18ygy7hqx824rldg82xhsqj5dyzcd98";
    };
  }
  {
    goPackagePath = "git.schwanenlied.me/yawning/newhope.git";
    fetch = {
      type = "git";
      url = "https://git.schwanenlied.me/yawning/newhope";
      rev = "9598792ba8f205d72c9b5b639b0d2827cbb7d8b9";
      sha256 = "1c9wy0l0xfinzzmjyjjwd7d3l2d8aj0sbcbhhwq1kbilbgxap8ni";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "b26d9c308763d68093482582cea63d69be07a0f0";
      sha256 = "0k7v2i1d2d6si8gswn83qb84czhhia53v2wdy33yz9ppdidxk0ry";
    };
  }
  {
    goPackagePath = "github.com/agl/ed25519";
    fetch = {
      type = "git";
      url = "https://github.com/agl/ed25519";
      rev = "5312a61534124124185d41f09206b9fef1d88403";
      sha256 = "1v8mhkf1m3ga5262s75vabskxvsw5rpqvi5nwhxwiv7gfk6h823i";
    };
  }
  {
    goPackagePath = "github.com/coreos/bbolt";
    fetch = {
      type = "git";
      url = "https://github.com/coreos/bbolt";
      rev = "48ea1b39c25fc1bab3506fbc712ecbaa842c4d2d";
      sha256 = "0r39wj5fv6d7nkkirjnnrnhikcp6sqa5dgmr6cimz5s0smvfm8vw";
    };
  }
  {
    goPackagePath = "github.com/dchest/siphash";
    fetch = {
      type = "git";
      url = "https://github.com/dchest/siphash";
      rev = "42ba037e748c9062a75e0924705c43b893edefcd";
      sha256 = "0ar74f8jgqa5cyr3kx1pj2wq9w6aavxkg0xfp6qq8f651lqanxfl";
    };
  }
  {
    goPackagePath = "github.com/eapache/queue";
    fetch = {
      type = "git";
      url = "https://github.com/eapache/queue";
      rev = "44cc805cf13205b55f69e14bcb69867d1ae92f98";
      sha256 = "07dp54n94gn3gsvdcki56yqh7py7wqqigxbamhxwgbr05n61fqyg";
    };
  }
  {
    goPackagePath = "github.com/emersion/go-message";
    fetch = {
      type = "git";
      url = "https://github.com/emersion/go-message";
      rev = "1716e3f473f914d0f63389271fbe851c749e0ab4";
      sha256 = "1yv8jw34hhdds66j547xw21z7rbzrxvdghdm1kwaxr006kw85ihi";
    };
  }
  {
    goPackagePath = "github.com/emersion/go-textwrapper";
    fetch = {
      type = "git";
      url = "https://github.com/emersion/go-textwrapper";
      rev = "d0e65e56babe3f687ff94c1d764ca0e6aa7723ee";
      sha256 = "1nw8qpjjbpkz49wd19yg2qsln1dmdfxi83wp2aa819cv6xxf2y7l";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/authority";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/authority";
      rev = "489f6f890182b1f2bb2b14f2dd337d4c417a504b";
      sha256 = "00rfnqln605kgjncxr9fp8qxxn03pdf6r5d2m0wmqavlby3kx8h8";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/core";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/core";
      rev = "feeb96ec57f1a1a39db22e83bc3af6ae8b1b13c7";
      sha256 = "17y0gc349cg4zjjjj6rq9wqa31jss9zds788h0qlwyfpsljx13aw";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/mailproxy";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/mailproxy";
      rev = "02d423f97784b8635030ae60bdf692623b7fc46b";
      sha256 = "180kn9mrxqwf65gp9bkmg7r25461fz027lnih3a2kji9f7qm2q8y";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/minclient";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/minclient";
      rev = "c42b729d286ac8da74fa16930553ef58531c127e";
      sha256 = "14rx15adyg3pahg1zz5vld95l5bz4nss8xqhlfxfm915wm2hnhf7";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/noise";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/noise";
      rev = "330b6cee8864fff2bad72f3d6cd6ba1dcdb2b877";
      sha256 = "0606id2rhgc87j6dyj2c1brbxw9pa0fq3al0h1gp51r9i2pig7n8";
    };
  }
  {
    goPackagePath = "github.com/katzenpost/server";
    fetch = {
      type = "git";
      url = "https://github.com/katzenpost/server";
      rev = "f9e8bd2275ab9be71a1bfb1c1287b1eeb3fcda3f";
      sha256 = "1msb7a992f3f7p3vy3rkfhfbv5g0r89i3hgbfzlipihsiiz4z57j";
    };
  }
  {
    goPackagePath = "github.com/siebenmann/smtpd";
    fetch = {
      type = "git";
      url = "https://github.com/siebenmann/smtpd";
      rev = "b93303610bbe1b2cc570daff2de7d77dfac329a0";
      sha256 = "1vncxcvm6rf1l5wcr29jl3gb2m6dvln8bvk7cgsj8r0jhnjikmy0";
    };
  }
  {
    goPackagePath = "github.com/ugorji/go";
    fetch = {
      type = "git";
      url = "https://github.com/ugorji/go";
      rev = "9831f2c3ac1068a78f50999a30db84270f647af6";
      sha256 = "0qxdq599sjwb03znlxy634mdnmfl90770wf1kk37dhzll6i84vkr";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "a6600008915114d9c087fad9f03d75087b1a74df";
      sha256 = "099vyf8133bjwaqcv377d9akam3j5xwamwqrihmjhvzbvqs649yc";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "5ccada7d0a7ba9aeb5d3aca8d3501b4c2a509fec";
      sha256 = "0bdwdxy2gz48icnh023r5fga3z4x6c8gry8jlfjqr5w12y3s281g";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "2c42eef0765b9837fbdab12011af7830f55f88f0";
      sha256 = "0gj9nwryyzf9rn33gl3zm6rxvg1zhrhwi36akipqj37x4g86h3gz";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "e19ae1496984b1c655b8044a65c0300a3c878dd3";
      sha256 = "1cvnnx8nwx5c7gr6ajs7sldhbqh52n7h6fsa3i21l2lhx6xrsh4w";
    };
  }
  {
    goPackagePath = "gopkg.in/eapache/channels.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/eapache/channels.v1";
      rev = "47238d5aae8c0fefd518ef2bee46290909cf8263";
      sha256 = "179ryd2rqsccnv5nk35f8j4nfbqr8cgb2bjm0j8isvf5nzks8s9y";
    };
  }
  {
    goPackagePath = "gopkg.in/op/go-logging.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/op/go-logging.v1";
      rev = "b2cb9fa56473e98db8caba80237377e83fe44db5";
      sha256 = "01a6lkpj5p82gplddh55az194s9y3014p4j8x4zc8yv886z9c8gn";
    };
  }
  {
    goPackagePath = "gopkg.in/square/go-jose.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/square/go-jose.v2";
      rev = "f8f38de21b4dcd69d0413faf231983f5fd6634b1";
      sha256 = "1bjrs3xq3m2ckfds0l4wqf81311ymm9agipmkllbvkadac156dsa";
    };
  }
]
